apiVersion: v1
kind: Service
metadata:
  name: "first-app-service"
  namespace: prod
spec:
  selector:
    run: "first-app"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer